<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\Escaper;

/**
 * @var \Mollie\Payment\Block\Applepay\Shortcut\Button $block
 * @var Escaper $escaper
 */

?>
<div id="mollie_applepay_minicart"
     class="mollie-applepay-minicart"
     x-data="prepareMollieApplePayMinicart"
>

    <div class="<?= $block->escapeHtmlAttr($block->getButtonClasses()); ?> cursor-pointer"
         @click="pay"
    >
        <span class="sr-only">Buy with</span>
        <span class="logo"></span>
    </div>
</div>
